# Base pricing template for new providers
# Copy this file and modify for your provider

provider: "provider_name"
currency: "USD"
unit: "per_1m_tokens"
models:
  model-name:
    input: 0.00
    output: 0.00
    # Optional fields:
    # original_provider: "if_via_aggregator"
    # region: "if_regional_pricing"
    # tier: "if_tiered_pricing"

metadata:
  last_updated: "YYYY-MM-DD"
  source: "pricing_source"
  notes: "Additional notes about pricing"
  version: "1.0"
  contributor: "your_name_or_handle"

# Pricing tiers example (uncomment if needed):
# tiers:
#   free:
#     input: 0.00
#     output: 0.00
#     limits: "1000 tokens/month"
#   pro:
#     input: 0.01
#     output: 0.02
#     limits: "unlimited"
