# Base pricing template for new providers
# Copy this file and modify for your provider

provider: "provider_name"
currency: "USD"
unit: "1MTok"
models:
  model-name:
    input: 0.00
    output: 0.00
    # Optional fields:
    # original_provider: "if_via_aggregator"
    # region: "if_regional_pricing"
    # tier: "if_tiered_pricing"  we only support standard tier pricing currently. 
    # cached_input: 0.00
    # 5m_cache_write: 0.00
    # 1h_cache_write: 0.00
    # cache_read: 0.00

metadata:
  last_updated: "YYYY-MM-DD"
  source: "pricing_source_url"
  notes: "Additional notes about pricing"
  version: "1.0"